version: "3.9"

services:
  llm-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hpclab-llm-bot
    volumes:
      - ./src:/code/src
      - tf-data:/root/.cache
    ports:
      - 8080:8080
      - 8000:8000
    environment:
      - CACHE_ADDRESS=${CACHE_ADDRESS}
    secrets:
      - vault-secrets.yml
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    depends_on:
      - cache

  dcgm_exporter:
    container_name: dcgm-exporter
    image: nvcr.io/nvidia/k8s/dcgm-exporter:2.4.6-2.6.10-ubuntu20.04
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    restart: always
    environment:
      - DCGM_EXPORTER_NO_HOSTNAME=1
    cap_add:
      - SYS_ADMIN
    ports:
      - "9400:9400"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8081:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
    - llm-bot

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    hostname: exporter
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    ports:
      - 9100:9100
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    networks:
      - default

  volume-exporter:
    container_name: volume-exporter
    image: mnadeem/volume_exporter
    volumes:
      - tf-data:/tmp/tf-data
      - cache-data:/tmp/cache-data
    command:
      - --volume-dir=model-data:/tmp/tf-data
      - --volume-dir=cache-data:/tmp/cache-data
    ports:
      - 9889:9888
    restart: unless-stopped
    networks:
      - default
  
  cache:
    container_name: redis-cache
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - cache-data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf

secrets:
  vault-secrets.yml:
    file: ./vault-secrets.yml

volumes:
  tf-data:
  cache-data:
