version: "3.9"

services:
  llm-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hpclab-llm-bot
    volumes:
      - ./src:/code
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl", "0.0.0.0:8080"]
      interval: 10s
      timeout: 30s
      retries: 5
    secrets:
      - vault-secrets.yml
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

secrets:
  vault-secrets.yml:
    file: ./vault-secrets.yml

volumes:
  code:
